config/routes.rb
Rails.application.routes.draw do
  root to: 'users#my_movie'
  # get '/users/my_movie' => 'users#my_movie', as: 'root'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/users/my_movie' => 'users#my_movie', as: 'my_movie'
  get '/users/my_tv' => 'users#my_tv', as: 'my_tv'
  resources :users
  # get '/users/new' => 'users#new'
  get '/recommends/rec_check' => 'recommends#rec_check'
  get '/whatsbetter/top_rated_movies' => 'whatsbetter#top_rated_movies', as: 'whatsbetter_top_rated_movies'
  resources :recommends
  get '/shows/imdb_cache' => 'shows#imdb_cache', as: 'imdb_cache'
  get '/shows/full_cast' => 'shows#full_cast', as: 'full_cast'
  get '/shows/show_why' => 'shows#show_why', as: 'show_why'
  get '/shows/user_mining' => 'shows#user_mining', as: 'user_mining'
  get '/shows/all_genres' => 'shows#all_genres', as: 'all_genres'
  get '/shows/genre' => 'shows#genre', as: 'genre'
  get '/shows/scrape' => 'shows#scrape', as: 'scrape'
  get '/shows/tv_tonight' => 'shows#tv_tonight', as: 'tv_tonight'
  get '/shows/dvd' => 'shows#dvd', as: 'dvd'
  get '/shows/imdb_search_title' => 'shows#imdb_search_title', as: 'imdb_search_title'
  resources :shows
  get '/whatsbetter/first_run' => 'whatsbetter#first_run', as: 'first_run'
  get '/whatsbetter/clear_skips' => 'whatsbetter#destroy_skips', as: 'clear_skips'
  get '/whatsbetter/rate_shows' => 'whatsbetter#rate_shows', as: 'rate_shows'
  get '/whatsbetter/top_rated' => 'whatsbetter#top_rated', as: 'whatsbetter_top_rated'
  get '/whatsbetter/rate_show' => 'whatsbetter#rate_show', as: 'rate_show'
  get '/whatsbetter/rate_group' => 'whatsbetter#rate_group', as: 'rate_group'
  get '/whatsbetter/rate_confusing' => 'whatsbetter#rate_confusing', as: 'rate_confusing'
  get '/whatsbetter/rate_show_recs' => 'whatsbetter#rate_show_recs', as: 'rate_show_recs'
  resources :whatsbetter
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/whatsbetter.rb
# frozen_string_literal: true

# Whatsbetter rating methods
class Whatsbetter < ApplicationRecord
  belongs_to :user
  validates :first, uniqueness: { scope: %i[second user_id] }
  validates :first, presence: true
  validates :second, presence: true

  # validate :validation

  # def validation
  #   errors.add(first, 'repeat') if whats_validation(first, second)
  # end

  # def whats_validation(first, second)
  #   w_at = Whatsbetter.arel_table
  #   return true if where(w_at[:first].eq(first))
  #     .and(where(w_at[:second].eq(second)))[0]

  #   return true if where(w_at[:first].eq(second))
  #     .and(where(w_at[:second].eq(first)))[0]
  # end
  # belongs_to :score

  # def self.cached
  #   @cached ||= Hash.new { |hsh, ky| hsh[ky] = {} }
  # end

  # def self.reset_imdb(imdb)
  #   cached[imdb] = {}
  # end

  def self.destroy_whats(user_id, first, second)
    where(user: user_id, first: first, second: second).delete_all
    where(user: user_id, first: second, second: first).delete_all
    UserScore.clear_scores([first, second], user_id)
  end

  def self.w_at
    arel_table
  end

  def self.wins(imdb)
    ratings(imdb).select do |rating|
      imdb == rating.first && rating.result == 1
    end
  end

  def self.losses(imdb)
    ratings(imdb).select do |rating|
      imdb == rating.second && rating.result == 1
    end
  end

  def self.ratings(imdbs)
    imdbs = [imdbs] if imdbs.class == String
    imdbs =
      imdbs.reduce([]) do |total, imdb|
        total.push(ratings_find(imdb))
      end
    imdbs.flatten
  end

  def self.ratings_find(imdb)
    where(w_at[:first].eq(imdb))
      .or(where(w_at[:second].eq(imdb)))
  end

  def self.newest(imdb)
    ratings_find(imdb)
      .order(updated_at: :desc)
      .limit(1).pluck(:updated_at)[0]
  end

  def self.skips(imdb)
    ratings(imdb).select { |rating| rating.result.zero? }
  end

  def self.last_match
    Show.shows_by_imdb([last.first, last.second])
  end
end

app/controllers/whatsbetter_controller.rb
# frozen_string_literal: true

# the whatsbetter rating controller
class WhatsbetterController < ApplicationController
  include ApplicationHelper
  # def top_rated
  #   @shows_matchup = Whatsbetter.matchup_quick_list(Show.tv)
  #   respond_to do |format|
  #     format.html { render(template: 'whatsbetter/rate.html.erb') }
  #   end
  # end

  # def top_rated_movies
  #   # @shows = Show.where('subtext not like "%TV%"').order(popluarity: :desc)
  #   show =
  #     Show.movies.find do |movie|
  #       score = ScoreService.new(current_user, movie)
  #       score.show_total < 1
  #     end
  #   @shows_matchup = show.match if show
  #   render(template: 'whatsbetter/rate.html.erb')
  # end

  def rate_show
    show = Show.find_by(imdb: params['show'])
    @show = show
    @shows_matchup = [show, MatchService.new(show, current_user).match]
    render(template: 'whatsbetter/rate.html.erb', layout: false)
  end

  def rate_shows
    shows = Show.where(imdb: params['shows']) # .sort_by(&:popularity)
    imdbs = shows.map(&:imdb)
    imdbs -= current_user.score.skippable(imdbs)

    imdb = imdbs.sort_by {|imdb| current_user.score_cache(imdb).total_against.length}[0]
    show = Show.show_by_imdb(
      imdb
    )
    m_serv = MatchService.new(show, current_user)
    # show = Show.show_by_imdb(imdbs[0])
    #       .find_by do |f_show|
    #         s_score = f_show.score(current_user)
    #     !s_score.already_scored? || s_score.skipped_against.count < 3 ||
    #       Show.show?(f_show.imdb)
    #   end
    @shows_matchup = [show, m_serv.match] if show
    @show = show
    render(template: 'whatsbetter/rate.html.erb', layout: false)
  end

  def rate_show_recs
    show = Show.find_by(imdb: params['show'])
    shows = Show.shows_by_imdb(show.recommend).push(show).shuffle!
    @show = shows[0]
    render(template: 'whatsbetter/rate.html.erb')
  end

  def rate_group
    imdbs = params['shows']
    imdbs = imdbs.shuffle if imdbs
    @shows_matchup = Show.shows_by_imdb(find_match_from_group(imdbs)) if imdbs
    render(template: 'whatsbetter/rate.html.erb', layout: false)
  end

  def rate_confusing
    @shows = current_user.confusing_rankings[0..5]
    render(template: 'whatsbetter/_rate_multiple.html.erb', layout: false)
  end

  def find_match_from_group(imdbs)
    imdbs.each do |imdb_a|
      f_imdb_b = MatchService.new(imdb_a, current_user)
                             .find_match(imdbs - [imdb_a])[0]
      return [imdb_a, f_imdb_b] if f_imdb_b
    end
  end

  def first_run
    # if this is the first run for the app, not just the user,
    # there may not be any shows in the db
    # and this will break
    # do something about this !!
    genres = Show.select('distinct unnest(genres)').map(&:unnest)
    shows =
      ['TV', 'MOVIE'].product(genres).map do |show_type, genre|
        Show.where("'#{genre}' = ANY(genres)")
            .where(show_type: show_type).where('popularity is not null')
            .where("'Adult' != ANY(genres)")
            .order(popularity: :desc).limit(5)
      end
    @shows = shows.flatten.compact.select {|show| show.recommend.length > 1}

    render(template: 'whatsbetter/first_run.html.erb')
  end

  def create
    imdbs = params[:name].split(':')
    if imdbs.length == 2
      create_normal(find_first, find_second)
    else
      create_multiple
    end
    redirect_back(fallback_location: root_path)
  end

  def create_normal(first, second)
    Whatsbetter.destroy_whats(current_user.id, first, second)

    Whatsbetter.new(
      user: current_user,
      first: first,
      second: second,
      result: result
    ).save
    # redirect_to(:back)
  end

  def create_multiple
    imdbs = imdbs_split
    if result.zero?
      # !! untested
      imdbs.combination(2).each { |i_a, i_b| create_normal(i_a, i_b) }
    else
      winner = imdbs.delete_at(params[:score].to_i - 1)
      imdbs.each { |second| create_normal(winner, second) }
    end
  end

  def destroy
    Whatsbetter.destroy_whats(current_user.id, params[:first], params[:second])
    redirect_to(:back, notice: 'rating destroyed.')
  end

  def destroy_skips
    imdb = params[:imdb]
    skips = current_user.whatsbetter.skips(imdb)
    UserScore.clear_scores([imdb], current_user.id)
    # skips = current_user.whatsbetter.where(first: imdb, result: 0)
    # skips += current_user.whatsbetter.where(second: imdb, result: 0)
    skips.each(&:destroy)
    redirect_to(:back)
  end

  def update
    redirect_to(whatsbetter_path)
  end

  private

  def whatsbetter_params
    params.require(:name).permit(:score)
  end

  # def create_winner(imdbs, result)
  #   result = (1 unless result.zero?) || 0
  #   wb = Whatsbetter.new(
  #     user: self,
  #     first: imdbs[0],
  #     second: imdbs[1],
  #     result: result
  #   )
  #   wb.save
  # end

  def imdbs_split
    params[:name].split(':')
  end

  def find_first
    find_score == 1 ? imdbs_split[0] : imdbs_split[1]
  end

  def find_second
    find_score == 1 ? imdbs_split[1] : imdbs_split[0]
  end

  def find_score
    params[:score].keys.first.to_i
  end

  # this doesnt seem to be working!
  def result
    (1 unless find_score.zero?) || 0
  end
end

app/views/whatsbetter/_rate.html.erb
  <% last_match = current_user.last_match %>
  <% if @shows_matchup && @shows_matchup.compact.length == 2 %>
  <% @shows_matchup = @shows_matchup.shuffle %>
  <%= form_tag({:action => 'create'}, {:id=> 'blah'}) %>
<table class="whatsbetter">
  <% if last_match %>
    <tr style="text-align:center; vertical-align:top;">
      <% last_match.each do |show| %>
        <td>
          <%= link_to(show.name, show) %><br>
      <%= render '/shows/score', show: show %>
        </td>
  <% end %>
    </tr>
  

<% end %>
  <tr><td colspan="2" style="text-align:center; vertical-align:top;">
      <%= hidden_field_tag :name, @shows_matchup[0].imdb + ':' + @shows_matchup[1].imdb %>
      <%= submit_tag( "Skip", :name => "score[0]") %>
    </td></tr>
  <tr>
    <% @shows_matchup[0..1].each_with_index do |show, i| %>
      <td class="whatsbetter" style="height: 80; width: 50; vertical-align:top">
        <%# submit_tag(i+1, :name => "score", :type => :image, :src => show.img_url) %>
        <%# submit_tag('blah', type: image, src: show.img_url, value: i+1) %>
        <%= image_submit_tag(show.img_url, name: "score[#{i+1}]") %>
        <h2 style="text-align: center"><%= link_to(show.name, show, target: "_parent") %></h2><p style="text-align: center"><%= show.subtext.gsub('|','<br>').html_safe %><br><small><%= show.popularity %></small></p>
    <% end %>
  </tr>

<% if @show && current_user.score_cache(@show.imdb).already_scored? %>
  <tr><td colspan="2" style="text-align:center"><%= link_to 'Done', @show, target: "_parent"  %></td></tr>

<script>
function myFunction() {
    window.top.location.reload();
}
</script>
<% end %>
</table>
<%end %>

app/views/whatsbetter/_rate_multiple.html.erb
<% if @shows.length > 1 %>
  <%= form_tag({:action => 'create'}, {:id=> 'blah'}) %>
<div class="whatsbetter" width = 100%>
    <div style="text-align:center; vertical-align:top;">
      <%= hidden_field_tag :name, @shows.map(&:imdb).join(':') %>
      <%= submit_tag( "Skip", :name => "score") %>
    </div>
    <p><%= @shows[0].name %></p>
    <% @shows.each_with_index do |show, i| %>
      <div style="float: left; width: 200; height: 500">
        <%= submit_tag(i+1, :name => "score", :type => :image, :src => show.img_url) %>
        <h2 style="text-align: center"><%= link_to(show.name, show, target: "_parent") %></h2>
        <p style="text-align: center">
          <%= show.subtext.gsub('|','<br>').html_safe %><br>
          <small><%= show.popularity %></small>
        </p>
      </div>
    <% end %>
</div>

<% end %>

app/views/whatsbetter/first_run.html.erb
<h2>Welcome to the Show Rater!!</h2>
<table>
  <tr><td align='center'>
<iframe src="<%= rate_shows_path(shows: @shows, first_run: 1) %>" width="500" height="600" style="border:none" align='center'>
</iframe>
    </td></tr>
    <tr align='center'><td>
<%= link_to 'Generate Your Movie!', my_movie_path %>
    </td></tr>
    <tr><td>
  <%= link_to 'Generate Your TV!', my_tv_path %>
    </td></tr>
</table>

app/views/whatsbetter/rate.html.erb
<%= render '/whatsbetter/rate.html.erb' %> 

app/views/whatsbetter/tonight.html.erb
<%#= form_tag (@whatsbetter, whatsbetter_path, :method => "PUT",  :id => "blah" ) do %>
  <%= form_tag({:action => 'create'}, {:id=> 'blah'}) %>
<table class="whatsbetter">
  <tr>
    <% @shows_matchup[0..1].each_with_index do |show, i| %>
      <td class="whatsbetter"><h2><%= show.name %></h2><br>
        <%= submit_tag(i+1, :name => "score", :type => :image, :src => show.img_url) %>
    <% end %>
  </tr>

  <tr><td colspan="2">
      <%= hidden_field_tag :name, @shows_matchup[0].imdb + ':' + @shows_matchup[1].imdb %>
      <%= submit_tag( "Skip", :name => "score") %>
      <%# submit_tag( "Skip", name:"[rs@shows&rs[]=0]") %>
    </td></tr>

</table>