config/routes.rb
Rails.application.routes.draw do
  root to: 'users#my_movie'
  # get '/users/my_movie' => 'users#my_movie', as: 'root'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/users/my_movie' => 'users#my_movie', as: 'my_movie'
  get '/users/my_tv' => 'users#my_tv', as: 'my_tv'
  resources :users
  # get '/users/new' => 'users#new'
  get '/recommends/rec_check' => 'recommends#rec_check'
  get '/whatsbetter/top_rated_movies' => 'whatsbetter#top_rated_movies', as: 'whatsbetter_top_rated_movies'
  resources :recommends
  get '/shows/imdb_cache' => 'shows#imdb_cache', as: 'imdb_cache'
  get '/shows/full_cast' => 'shows#full_cast', as: 'full_cast'
  get '/shows/show_why' => 'shows#show_why', as: 'show_why'
  get '/shows/user_mining' => 'shows#user_mining', as: 'user_mining'
  get '/shows/all_genres' => 'shows#all_genres', as: 'all_genres'
  get '/shows/genre' => 'shows#genre', as: 'genre'
  get '/shows/scrape' => 'shows#scrape', as: 'scrape'
  get '/shows/tv_tonight' => 'shows#tv_tonight', as: 'tv_tonight'
  get '/shows/dvd' => 'shows#dvd', as: 'dvd'
  get '/shows/imdb_search_title' => 'shows#imdb_search_title', as: 'imdb_search_title'
  resources :shows
  get '/whatsbetter/first_run' => 'whatsbetter#first_run', as: 'first_run'
  get '/whatsbetter/clear_skips' => 'whatsbetter#destroy_skips', as: 'clear_skips'
  get '/whatsbetter/rate_shows' => 'whatsbetter#rate_shows', as: 'rate_shows'
  get '/whatsbetter/top_rated' => 'whatsbetter#top_rated', as: 'whatsbetter_top_rated'
  get '/whatsbetter/rate_show' => 'whatsbetter#rate_show', as: 'rate_show'
  get '/whatsbetter/rate_group' => 'whatsbetter#rate_group', as: 'rate_group'
  get '/whatsbetter/rate_confusing' => 'whatsbetter#rate_confusing', as: 'rate_confusing'
  get '/whatsbetter/rate_show_recs' => 'whatsbetter#rate_show_recs', as: 'rate_show_recs'
  resources :whatsbetter
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recommend.rb
# frozen_string_literal: true

# Recommend Table Methods
class Recommend < ApplicationRecord
  validates :first, presence: true
  validates :second, presence: true
  validates :first, uniqueness: { scope: [:second] }
  validate :first_not_second
  # belongs_to :show, foreign_key: 'first'

  def first_not_second
    errors.add(:first, 'cant equal second') if first == second
  end

  def self.rec_check(score)
    recs = Recommend.where(first: score.imdb).pluck(:second)
    recs.each do |rec|
      rec_scores = Score.where(imdb: rec)
      bad = rec_scores.where('show_score < 40')
      # delete_rec(rec, score) if rec_scores.count > 50 &&
      delete_rec(rec, score) if rec_scores.count > 10 &&
                                bad.count > rec_scores.count / 2
    end
  end

  def self.delete_rec(rec, score)
    ApplicationRecord.errors.push("deleted rec! #{rec} from #{score.imdb} ")
    Recommend.find_by(first: score.imdb, second: rec).delete

    Score.clear_score(nil, Show.show_by_imdb(rec))
  end

  def self.recs_check
    scores = Score.select('count(*), imdb').where('show_score > 80')
                  .group(:imdb).order(count: :desc)
    scores = scores.select { |score| score.count > 10 }
    scores.each { |score| rec_check(score) }
  end

  # used by User
  def self.group_recommend(imdbs)
    (Recommend.where(first: imdbs).pluck(:second).compact.uniq +
     Recommend.where(second: imdbs).pluck(:first).compact.uniq).uniq
  end

  def self.clean_recs(show)
    shows = Show.shows_by_imdb(show.recommendations.pluck(:second))
    shows = MatchService.new(show).sort_by_genres(shows)[15..-1] if shows
    Recommend.where(first: show.imdb, second: shows).delete_all if shows
  end

  def self.create_recs(imdb, imdbs, source)
    # ApplicationRecord
    #   .errors("Found #{shows[0..11].count} Recs for #{current_show.imdb}")
    shows = Show.shows_by_imdb(imdbs)
    c_show = Show.show_by_imdb(imdb)
    shows = shows.select { |show| c_show.relevant?(show) }
    shows.map do |second|
      next if second.imdb == imdb
      Recommend.create_with(source: source)
               .find_or_create_by(first: imdb, second: second.imdb)
    end
  end
end

app/controllers/recommends_controller.rb
# frozen_string_literal: true

# for recommendations
class RecommendsController < ApplicationController
  before_action :set_recommend, only: %i[show edit update destroy]

  # GET /recommends
  # GET /recommends.json
  def index
    @shows = get_recs('TV')
    @back_path = recommends_path
    respond_to do |format|
      format.html { render(template: 'shows/index') }
    end
  end

  def rec_check
    # Recommend.recs_check
    # imdbs = current_user.favorites

    rec_clear
    diffs = current_user.score.suprisings_rec_scores
    @notice = "#{diffs[0] / diffs[1].length} out of #{diffs[1].length}"
    @shows  = Show.shows_sorted_by_imdb(diffs[1][0..49])
    render(template: 'shows/index')
  end

  def rec_clear
    scores = current_user.score.where('show_total > 5').where("imdb like 'tt%'")
    scores.each do |score|
      score.update(
        show_total: nil, show_score: nil, won_against: nil, lost_against: nil,
        rec_total: nil, rec_score: nil
      )
      score.fill_score
    end
  end

  def rec_check_diff
    current_user.suprising_rec_scores
  end

  def rec_check_diff_old(imdbs)
    Show.shows_by_imdb(imdbs).reduce(0) do |sum, show|
      diff = rec_check_show_diff(
        show.score(current_user).rec_score,
        show.score.show_score
      )
      diff == Float::INFINITY || show.score.rec_score == -1 ? sum : sum + diff
    end
  end

  def rec_check_show_diff(rec_score, show_score)
    diff = ((show_score - rec_score) / Float(rec_score)) * 100
    diff == Float::INFINITY ? nil : diff
    # show_diff = show_score if show_diff == Float::INFINITY || show_diff.nan?
    # if rec_score > show_score
    #   (rec_score - show_score) / Float(show_score)
    # else
    #   (show_score - rec_score) / Float(rec_score)
    # end
  end

  # GET /recommends/1
  # GET /recommends/1.json
  def show; end

  # GET /recommends/new
  def new
    @recommend = Recommend.new
  end

  # GET /recommends/1/edit
  def edit; end

  # POST /recommends
  # POST /recommends.json
  def create
    recommend = Recommend.new(recommend_params)
    if recommend.save
      redirect_to(recommend, notice: 'Recommend created.')
    else
      render(:new)
    end
  end

  # PATCH/PUT /recommends/1
  # PATCH/PUT /recommends/1.json
  def update
    if recommend.update(recommend_params)
      redirect_to(recommend, notice: 'Recommend updated.')
    else
      render(:edit)
    end
  end

  # DELETE /recommends/1
  # DELETE /recommends/1.json
  def destroy
    recommend.destroy!
    respond_to do |format|
      format.html do
        redirect_to(
          recommends_url,
          notice: 'Recommend was successfully destroyed.'
        )
      end
    end
  end

  private

  def recommend
    @recommend ||= Recommend.find(params[:id])
  end

  def recommend_params
    params.require(:recommend).permit(:first, :second)
  end
end

app/views/recommends/_form.html.erb
<%= form_for(recommend) do |f| %>
  <% if recommend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recommend.errors.count, "error") %> prohibited this recommend from being saved:</h2>

      <ul>
      <% recommend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first %>
    <%= f.text_area :first %>
  </div>

  <div class="field">
    <%= f.label :second %>
    <%= f.text_area :second %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recommends/edit.html.erb
<h1>Editing Recommend</h1>

<%= render 'form', recommend: @recommend %>

<%= link_to 'Show', @recommend %> |
<%= link_to 'Back', recommends_path %>

app/views/recommends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recommends</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Second</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recommends.each do |recommend| %>
      <tr>
        <td><%= recommend.first %></td>
        <td><%= recommend.second %></td>
        <td><%= link_to 'Show', recommend %></td>
        <td><%= link_to 'Edit', edit_recommend_path(recommend) %></td>
        <td><%= link_to 'Destroy', recommend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recommend', new_recommend_path %>

app/views/recommends/new.html.erb
<h1>New Recommend</h1>

<%= render 'form', recommend: @recommend %>

<%= link_to 'Back', recommends_path %>

app/views/recommends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @recommend.first %>
</p>

<p>
  <strong>Second:</strong>
  <%= @recommend.second %>
</p>

<%= link_to 'Edit', edit_recommend_path(@recommend) %> |
<%= link_to 'Back', recommends_path %>