config/routes.rb
Rails.application.routes.draw do
  root to: 'users#my_movie'
  # get '/users/my_movie' => 'users#my_movie', as: 'root'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/users/my_movie' => 'users#my_movie', as: 'my_movie'
  get '/users/my_tv' => 'users#my_tv', as: 'my_tv'
  resources :users
  # get '/users/new' => 'users#new'
  get '/recommends/rec_check' => 'recommends#rec_check'
  get '/whatsbetter/top_rated_movies' => 'whatsbetter#top_rated_movies', as: 'whatsbetter_top_rated_movies'
  resources :recommends
  get '/shows/imdb_cache' => 'shows#imdb_cache', as: 'imdb_cache'
  get '/shows/full_cast' => 'shows#full_cast', as: 'full_cast'
  get '/shows/show_why' => 'shows#show_why', as: 'show_why'
  get '/shows/user_mining' => 'shows#user_mining', as: 'user_mining'
  get '/shows/all_genres' => 'shows#all_genres', as: 'all_genres'
  get '/shows/genre' => 'shows#genre', as: 'genre'
  get '/shows/scrape' => 'shows#scrape', as: 'scrape'
  get '/shows/tv_tonight' => 'shows#tv_tonight', as: 'tv_tonight'
  get '/shows/dvd' => 'shows#dvd', as: 'dvd'
  get '/shows/imdb_search_title' => 'shows#imdb_search_title', as: 'imdb_search_title'
  resources :shows
  get '/whatsbetter/first_run' => 'whatsbetter#first_run', as: 'first_run'
  get '/whatsbetter/clear_skips' => 'whatsbetter#destroy_skips', as: 'clear_skips'
  get '/whatsbetter/rate_shows' => 'whatsbetter#rate_shows', as: 'rate_shows'
  get '/whatsbetter/top_rated' => 'whatsbetter#top_rated', as: 'whatsbetter_top_rated'
  get '/whatsbetter/rate_show' => 'whatsbetter#rate_show', as: 'rate_show'
  get '/whatsbetter/rate_group' => 'whatsbetter#rate_group', as: 'rate_group'
  get '/whatsbetter/rate_confusing' => 'whatsbetter#rate_confusing', as: 'rate_confusing'
  get '/whatsbetter/rate_show_recs' => 'whatsbetter#rate_show_recs', as: 'rate_show_recs'
  resources :whatsbetter
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/show.rb
# frozen_string_literal: true

# The Show Model
class Show < ApplicationRecord
  self.primary_key = 'imdb'
  # serialize :creators, Array
  # serialize :actors, Array
  # serialize :genres, Array
  # serialize :alt_names, Array
  validates :imdb, uniqueness: true, presence: true
  validate :imdb_valid
  # validates :imdb, length: { is: 9 }
  has_many :recommendations, class_name: 'Recommend', foreign_key: 'first'

  # dont think i use this anymore

  include ShowAttr

  def imdb_valid
    # !! newly added
    # dont know why this is necessary
    return false unless imdb
    imdb[0..1] == 'tt' || 'nm'
  end

  def self.shows_by_title(title)
    Show
      .where('name ilike :q', q: "%#{title}%")
      .order(popularity: :desc)
  end

  # called by: score.build_person, show_attr, shows_controller
  def self.shows_by_person(person, job = nil, limit = 3)
    # ImdbService.search(person) if update == true
    job ||= people_attrs.join("[0:#{limit}] || ")
    Show.where("? = ANY(#{job}[0:#{limit}])", person)
        .where("imdb not like 'ttmy%'")
  end

  # used by PeopleService
  def self.person_create(lnk, person_type)
    binding.pry if lnk.nil?
    imdb = ImdbService.link_to_imdb(lnk)
    img = ImdbService.person_link_to_img(lnk)
    # sometimes, esp directors, will be actors,
    # and a new img will be found for a preexisting person
    show = create_with(
      name: ImdbService.link_to_name(lnk),
      subtext: '',
      show_type: person_type,
      img_url: img
    ).find_or_create_by(imdb: imdb).person_img(img)
    show.imdb
  end

  # used by user_shows
  def self.people_by_job(job, imdbs)
    shows = select('unnest(' + job + '[0:3]) as person')
            .where(imdb: imdbs)
    people = shows.map(&:person)
    people.sort_by_freq![-(people.uniq.length / 10)..-1]
  end

  def self.favorite_attrs(imdbs, attr, s_range = (0..-1))
    attr =
      shows_by_imdb(imdbs).select { |show| show[attr] }
          .map { |show| show[attr][s_range] }.flatten.sort_by_freq!
    attr.length > 3 ? attr.compact[-3..-1].reverse : []
  end

  def self.favorite_cert(imdbs)
    [favorite_attrs(imdbs, 'certificate', (0..0))[0]] +
      favorite_attrs(imdbs, 'certificate', (1..-1))
  end

  def main_jobs
    jobs = %w[actors writing]
    jobs.push(show_type == 'MOVIE' ? 'directed' : 'produced')
  end

  # limit defaults to nil and not 0
  # in case i actually the first actors
  def people(jobs = main_jobs, limit = nil)
    jobs.each_with_object([]) { |ky, people| people += find_job(ky, limit) }
  end

  def find_job(ky, limit)
    ky_limit = limit || ky == 'actors' ? 2 : 0
    # ! to_a in case nil
    self[ky].to_a[0..ky_limit].map { |person| [person, '_', ky].join }
  end

  # people_attrs are the different types of jobs a person can have, e.g. actor, director, etc
  # this method should find all the people that fill those positions for this show.
  # !! GIVING UP ON GETTING THIS TO WORK
  def full_cast
    people_attrs.each_with_object([]) do |ky, cast|
      cast += set_job(ky)
    end
  end

  # as always, people are a kind of 'Show'
  # so this can read as get a sorted list of people by a job
  def set_job(ky)
    # job = Show.shows_sorted_by_imdb(self[ky])
    job = Show.shows_sorted_by_imdb([imdb])
    job.to_a.each { |person| person.show_type = ky }
    job
  end

  def person_img(img)
    update(img_url: img) unless self[:img_url] && self[:img_url] != ''
    self
  end

  # ! need to replace all show.find_by(imdb)
  # ! need to test imdbs for junk
  # !! need to reset people_vars when creating new show
  def self.show_by_imdb(imdb, show_info = {})
    show = find_by(imdb: imdb)
    unless show
      # !! newly added
      # needs fixing
      return nil unless imdb
      # show = create_with(show_info)
      show = find_or_create_by!(imdb: imdb)
      show.people_parser if person?(show.imdb)
    end

    set_show_info(show, show_info) if show_info

    show
  end

  def self.person_by_imdb(p_imdb, show)
    person = find_by(imdb: p_imdb)
    unless person || show.imdb[2..3] == 'my'
      # people_attrs.each { |ky| show[ky] = nil }
      # show.save
      show.people_parser
      person = find_by(imdb: p_imdb)
    end
    person || Show.create(imdb: p_imdb, img_url: '')
  end

  def self.shows_by_imdb(imdbs, show_info_hash = {})
    if imdbs.length > 100
      ApplicationRecord.errors(
        "big shows_by_imdb call #{imdbs.length} "
      )
    end
    (imdbs - where(imdb: imdbs).pluck(:imdb))
      .each { |imdb| show_by_imdb(imdb, show_info_hash[imdb]) }
    where(imdb: imdbs)
    # shows.map { |show| set_show_info(show, show_info_hash[show.imdb]) }
  end

  def self.set_show_info(show, show_info)
    show_info ||= {}
    show_info.each do |attr, val|
      show[attr] ||= val
    end
    show
  end

  # get a list of shows (or people) relevant to imdbs
  # and sort into a hash
  def self.shows_sorted_by_imdb(imdbs, show_info_hash = {})
    shows = shows_by_imdb(imdbs, show_info_hash)
    hash_object =
      shows.each_with_object({}) do |show, hash|
        hash[show.imdb] = show
      end
    imdbs.map { |index| hash_object[index] }
  end

  def self.shows_sorted_by_score(shows, current_user)
    # shows.to_a.sort_by(&:popularity)
    # shows.to_a.sort_by{|show|show.score(current_user.rec_score)}
    shows.sort_by do |show|
      [show.score(current_user)[:rec_score] || -1, show[:popularity].to_i || 0]
    end
  end

  # used by match_service
  def self.shows_by_genre(genres, show_type = %w[MOVIE TV], popularity = 0)
    # select(:imdb, :show_type, :genres, :certificate, :popularity)
    where('ARRAY[?] && genres', genres)
      .where(show_type: show_type)
      .where("popularity > #{popularity}")
      .where("imdb not like 'ttmy%'")
  end

  
  def self.shows_by_external_link(link_name, link_ids)
    qury = link_ids.to_s.tr('"', "'").delete('[').delete(']')
    Show.where("external_links ->> '#{link_name}' IN (#{qury})")
        # .pluck(:external_links)
        # .map { |e_links| e_links[link_name] }
  end

  def self.tv_tonight(start_date, end_date)
    # tvshows = Show.where(first_aired: todays_date)
    tvshows = ImdbService.tv_today(start_date, end_date) # if tvshows.empty?
    # tvshows = TvdbService.new_today if tvshows.empty?
    # tvshows = SimklService.tv_today(todays_date) if tvshows.empty?
    tvshows.to_a.compact
  end

  # used by user
  def self.favorite_actors(favs)
    # cant use pluck with the select [0:5]. cant figure another way
    actors = select('actors[0:2]').where(imdb: favs).map(&:actors).flatten
    actors.sort_by_freq![-(actors.uniq.length / 10)..-1]
  end

  def self.fill_people(imdbs)
    where(actors: nil).where(imdb: imdbs).find_each do |show|
      PeopleService.new(show)
    end
  end
  def relevant?(r_show)
    show_type == r_show.show_type &&
      r_show.popularity * 5 > popularity &&
      r_show.certificate[0] == certificate[0]
  end

  def score(current_user = nil)
    if show_type == 'internet_error'
      ApplicationRecord.errors.push(
        "score.show_type == 'internet error': #{caller[1]} "
      )
    end
    @score ||= current_user.score_cache(imdb, show_type)
  end

  def genres_comp_array(oshow_genres)
    cnt = (genres & oshow_genres).count
    [
      cnt,
      (genres.count - cnt).abs * -1,
      popularity
    ]
  end
end

app/controllers/shows_controller.rb
# frozen_string_literal: true

# Show Controller
class ShowsController < ApplicationController
  # before_action :set_show, only: %i[show edit update destroy]
  before_action :set_user

  # GET /shows
  # GET /shows.json
  def index
    qury = params[:q]
    # ! why would i run shows_by_person (which expects an imdb)
    # ! when i search for something??
    shows ||= Show.shows_by_person(qury, nil, 3) + Show.shows_by_title(qury)
    shows = Show.shows_sorted_by_score(shows, current_user)
    @qury = qury
    @shows = shows.reverse
  end

  def imdb_search_title
    qury = params['q']
    shows = Show.shows_sorted_by_score(ImdbService.search(qury), current_user)
    #            .sort_by do |show|
    #   [show.score(current_user).rec_score, show.popularity]
    # end
    @qury = qury
    @shows = shows.reverse!
    render('/shows/index')
  end

  def imdb_cache
    @show = current_show
  end

  def all_genres; end

  def genre
    genre = params['genre']
    shows =
      Show.shows_by_genre(genre).sort_by do |show|
        [show.score(current_user).rec_score(false), show.popularity]
      end
    @qury = '&genres=' + genre
    @shows = shows[0..99]
    render('/shows/index')
  end

  def tv_tonight
    # tvshows = Show.where(first_aired: TvdbService.todays_date)
    # tvshows = TvdbService.new_today if tvshows.empty?
    # tvshow = Show.tv_tonight
    # tvshows.to_a
    start_date = params['start_date'] || ApplicationRecord.todays_date
    end_date = params['end_date'] || ApplicationRecord.todays_date
    shows =
      Show.tv_tonight(start_date, end_date).sort_by do |show|
        [current_user.score_cache(show.imdb).rec_score, show.popularity]
      end
    @shows = shows.reverse
    @heading = "TV For #{start_date}-#{end_date}"
    render('/shows/index')
  end

  def full_cast
    shows = current_show.full_cast
    @shows = shows
    render('/shows/index')
  end

  def dvd
    @shows = ImdbService.dvd
    respond_to do |format|
      format.html { render('/shows/index') }
    end
  end

  def show_why
    @show = Show.show_by_imdb(params['show'])
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    if Show.person?(current_show.imdb)
      limit = params[:limit] ? 100 : 3
      shows = Show.shows_by_person(current_show.imdb, nil, limit)
      @shows = Show.shows_sorted_by_score(shows, current_user).reverse
      @show = current_show
      render('/shows/index')
    else
      @show = current_show
    end
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # def scrape
  #   Scraper.scrape
  # end

  # GET /shows/1/edit
  def edit; end

  def user_mining
    # scrape = current_user.id == 3 ? true : false
    # scrape_reviewers(current_show) if current_user.id == 3
    current_show.expand_recs
    # User.user_mining(current_show)
    # @show = current_show
    redirect_to(current_show)
  end

  # POST /shows
  # POST /shows.json
  def create
    show = Show.new(imdb: show_params[:imdb])
    show.save!
    respond_to do |format|
      format.html { redirect_to(shows_url, notice: 'Show created.') }
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    # respond_to do |format|
    if current_show.update(show_params)
      redirect_to(current_show, notice: 'Show updated.')
      # format.json { render :show, status: :ok, location: @show }
    else
      render(:edit)
      # format.json { render json: @show.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    current_show.destroy!
    respond_to do |format|
      format.html { redirect_to(shows_url, notice: 'Show destroyed.') }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def current_show
    # need a check for bogus show
    # imdb = params[:id]
    @current_show = Show.show_by_imdb(params[:id])
    # @show ||= Show.new(imdb: imdb)
  end

  def set_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def show_params
    params.require(:show).permit(:name, :imdb)
  end
end

app/views/shows/_form.html.erb
<%= form_for(show) do |f| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :imdb %>
    <%= f.text_area :imdb %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/_people.html.erb
<% a_show = Show.person_by_imdb(person, @show)%>
<% a_show.show_type = job %>
<%= image_tag(a_show.img_url) if a_show.img_url != 'internet error' %>
<%# link_to a_show.name, shows_path(actor: person) %>
<%= link_to a_show.name, a_show %>
<%= a_c = a_show.score(current_user).show_score.to_i; a_c if a_c > -1 %> |

app/views/shows/_score.html.erb
<% to_update = true unless to_update == false %>
<% score = show.score(current_user) %>
<% rec_score = to_update ? (score.rec_score ? score.rec_score.to_s : '?') : (score[:rec_score] ? score[:rec_score].to_s : '?')  %>
<% rec_score = '?' if rec_score == '-1' %>
<table><tr height=0>
<% if score.already_scored?(to_update) %>
  <td>
  <strong>Your Score: </strong>
  <%= link_to(score.show_score.to_i, show_why_path(show: show.imdb)) %>
  </td>
  <% if current_user.id == 3 %>
      <td>
        <%= rec_score %>
      </td>
  <% end %>
<% else %>
  <td style="padding: 0">
  <%= link_to('Estimated Score: ' + rec_score, show_why_path(show: show.imdb)) %>
  </td>
  <% if current_user.id == 3 %>
      <td>
        <%= score.show_score.to_i %>
      </td>
  <% end %>
<% end %>
  </tr></table>

app/views/shows/all_genres.html.erb
<%
    genres = ["Horror", "Reality-TV", "Sport", "Action", "Mystery", "Thriller", "News", "Family", "Comedy", "Adventure", "Talk-Show", "Crime", "History", "Documentary", "Romance", "Drama", "Fantasy", "Music", "Short", "Western", "Musical", "Sci-Fi", "Animation", "Biography", "War", "Game-Show", "Adult"]
  %>

<ul>
<% genres.each do |genre| %>
  <li> <%= link_to(genre, genre_path(genre: genre) ) %> </li>
<% end %>
</ul>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/imdb_cache.html.erb
<%= @show.imdb_cache.html_safe %>

app/views/shows/index.html.erb
<%#
  heading = '' unless @qury
  heading ||= if @qury[0..1] == 'tt'
              ['<a href="/shows/imdb_search_title?q=', @qury, '">search imdb</a>'
        ].join
            else
              ['<img height="100" src="', Show.show_by_imdb(@qury).img_url,
               '">', "<a href=/shows/#{@qury.html_safe}?limit=100>search deeper</a>",'<a href="/shows/imdb_search_title?q=', @qury,
              '">search imdb</a>'].join
            end
          %>


        <% to_update = false %>
<table>
  <tr>
    <% if @show && @show.img_url %>
    <td><%= image_tag(@show.img_url, height: "100", alt: "") %></td>
  <% end %>
    <% if @show && @show.imdb[0..1] == 'nm' %>
    <td><%= link_to('Search Deeper', show_path(id: @show.imdb, limit: 100)) %></td>
  <% end %>
  <% if @show || @qury %>
    <td><%= link_to('Search IMDB', imdb_search_title_path(q: (@qury || @show.imdb))) %></td>
  <% end %>
  </tr>
</table>
  <% if @heading %><h1><%=@heading%></h1>
<% else %><h1>Shows</h1>
<% end %>

<table>
  <thead>
    <tr>
      <th colspan="2">Name</th>
      <th>Imdb</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <%# next unless show.img_url %>
      <tr>
        <td> <%= image_tag(show.img_url, height: "40", alt: "") if show.img_url %> </td>
        <td><%= link_to show.name, show %></td>
        <td>
          <% unless show.imdb.nil? %> 
            <%= link_to show.imdb, 'http://www.imdb.com/title/' + show.imdb %> 
          <% else %>
            <%= form_for show do |f| %>
              <%= f.text_area :imdb %>
              <%= f.submit 'add imdb' %>
            <% end %>
          <% end %>
        </td>
        <td><%= show.show_type %></td>
        <td><%= show.subtext %></td>
        <td>
          <%= render '/shows/score', show: show, current_user: current_user, to_update: to_update %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%# render '/whatsbetter/rate', show: @shows.shuffle[0] %>
<% unless @shows.empty? || @shows[0].imdb[0..1] == 'nm' %>
  <iframe src="<%= rate_shows_path(shows: @shows.to_a[0..50]) %>" width="700" height="600" style="border:none">
</iframe>
<% end %>
<br>
<%= link_to 'More', request.query_parameters.merge(offset: @offset + 1) if @offset %>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <div style="float: left; padding: 20px">
<%= image_tag(@show.img_url, height: "200", alt: "") if @show.img_url %>
  </div>
  <h1><%= @show.name %></h1>
  </div>
</div>
<p>
  <strong>Imdb:</strong>
  <%= link_to @show.imdb, 'http://www.imdb.com/title/' + @show.imdb %><br>
  <%= link_to 'cache', imdb_cache_path(id: @show.imdb) if current_user.id == 3 %>
  <strong><%= @show.rating %></strong>
  <small><%= @show.popularity %></small><br>
<small><%= @show.certificate %></small>
</p>
<p> <%= @show.external_links %></p>
<p><%= @show.subtext %></p>
<p>
  <%= @show.description %>
</p>

<p>
  <%= render '/shows/score', show: @show %>
</p>

<p>
<%= @show.genres %><br>
<%= link_to('all genres', all_genres_path) %>
</p>

<% t = Time.now %>
<p>
  <strong>Actors:</strong>
  <% @show.actors[0..2].each do |person| %>
    <%= render '/shows/people', person: person, job: 'actors' %>
  <% end %>
</p>
<% if @show.show_type == 'TV' %>
<p>
  <strong>Writing:</strong>
  <% @show.writing[0..2].each do |person| %>
    <%= render '/shows/people', person: person, job: 'writing' %>
  <% end %>
</p>

<% else %>
<p>
  <strong>Directed by:</strong>
  <% @show.directed[0..2].each do |person| %>
    <%= render '/shows/people', person: person, job: 'directed' %>
  <% end %>
</p>
<% end %>

<p>
  <%= link_to 'Full Cast & Crew', full_cast_path(id: @show.imdb) %>
</p>
  <h2>Recommends:</h2>
  <% unless @show.imdb[2..3] == 'my' %>
  <p>
  <%= link_to 'Get More!', user_mining_path(id: @show.imdb) %>
  </p>
<% end %>
<table>
  <% Show.shows_by_imdb(@show.recommend).to_a.uniq.each do |rec_show| %>
  <tr>
    <td>
      <% rec_show.name unless rec_show[:name] %>
      <%= link_to rec_show[:name], rec_show %></td>
    <td style="padding: 0">
      <%= render '/shows/score', show: rec_show %>
    </td>
  </tr>
<% end %>
</table>
  <h2>Back Links:</h2>
<table>
  <% Show.shows_by_imdb(@show.back_recommend - @show.recommend).each do |rec_show| %>
  <tr>
    <td>
      <% rec_show.name unless rec_show[:name] %>
      <%= link_to rec_show[:name], rec_show %></td>
    <td style="padding: 0">
      <%= render '/shows/score', show: rec_show %>
    </td>
  </tr>
<% end %>
</table>


<table>
  <p>Lost Against: <%= @show.score(current_user).lost_against.count %></p>
  <% Show.shows_by_imdb(@show.score(current_user).lost_against[0..50]).each do |whats_show| %>
    <tr>
      <td><%= link_to whats_show.name, whats_show %></td>
    <td>
      <%= render '/shows/score', show: whats_show %>
    </td>
      <td><%= link_to "Delete", whatsbetter_path(id: 0, first: whats_show.imdb, second: @show.imdb), :method => :delete, :class => "delete", :confirm => "Are you sure ?"%>  </td>
    </tr>
  <% end %>
</table>

<table>
  <p>Won Against: <%= @show.score(current_user).won_against.count %></p>
  <% Show.shows_by_imdb(@show.score(current_user).won_against).each do |whats_show| %>
    <tr>
      <td><%= link_to whats_show.name, whats_show %> </td>
    <td style="padding: 0">
      <%= render '/shows/score', show: whats_show %>
    </td>
      <td><%= link_to "Delete", whatsbetter_path(id: 0, first: @show.imdb, second: whats_show.imdb), :method => :delete, :class => "delete", :confirm => "Are you sure ?"%>  </td>
    </tr>
  <% end %>
</table>


<table>
  <td>Skip Count</td> <td><%= current_user.score_cache(@show.imdb).skipped_against.count %></td><td><%= link_to 'Clear Skips', clear_skips_path(imdb: @show.imdb) %></td>
</table>


<% @rate_path ||= rate_show_path(show: @show) %>
<iframe src="<%= @rate_path %>" width="700" height="600" style="border:none">
</iframe>
<% if @show.imdb[2..3] == 'my' %>
<iframe src="<%= rate_group_path(shows: @show.score.won_against) %>" width="700" height="600" style="border:none">
</iframe>
<% end %>

<%= link_to 'Back', shows_path %>

app/views/shows/show_why.html.erb
<table>
  <tr>
    <th>name</th>
    <th>score</th>
    <th>won against</th>
    <th>won against count (<%= @show.score(current_user).total_wins.count %>)</th>
  </tr>
  <% @show.score(current_user).won_against.map { |imdb| Show.show_by_imdb(imdb) }.sort_by{ |show| show.score(current_user).show_score}.each do |a_show| %>
  <tr>
    <%# a_show = Show.show_by_imdb(a_imdb) %>
    <td><%= link_to(a_show.name, a_show) %></td>
    <td><%= a_show.score(current_user).show_score %></td>
    <td><%= a_show.score.won_against %></td>
    <td><%= a_show.score.won_against.length %></td>
  </tr>
<% end %>
</table>
<table>
  <tr>
    <th>name</th>
    <th>score</th>
    <th>lost against</th>
    <th>lost against count(<%= @show.score(current_user).total_losses.count %>)</th>
  </tr>
  <% @show.score(current_user).lost_against.map { |imdb| Show.show_by_imdb(imdb) }.sort_by{ |show| show.score(current_user).show_score}.each do |a_show| %>
  <tr>
    <td><%= link_to(a_show.name, a_show) %></td>
    <td><%= a_show.score(current_user).show_score %></td>
    <td><%= a_show.score.lost_against %></td>
    <td><%= a_show.score.lost_against.length %></td>
  </tr>
<% end %>
</table>