config/routes.rb
Rails.application.routes.draw do
  root to: 'users#my_movie'
  # get '/users/my_movie' => 'users#my_movie', as: 'root'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/users/my_movie' => 'users#my_movie', as: 'my_movie'
  get '/users/my_tv' => 'users#my_tv', as: 'my_tv'
  resources :users
  # get '/users/new' => 'users#new'
  get '/recommends/rec_check' => 'recommends#rec_check'
  get '/whatsbetter/top_rated_movies' => 'whatsbetter#top_rated_movies', as: 'whatsbetter_top_rated_movies'
  resources :recommends
  get '/shows/imdb_cache' => 'shows#imdb_cache', as: 'imdb_cache'
  get '/shows/full_cast' => 'shows#full_cast', as: 'full_cast'
  get '/shows/show_why' => 'shows#show_why', as: 'show_why'
  get '/shows/user_mining' => 'shows#user_mining', as: 'user_mining'
  get '/shows/all_genres' => 'shows#all_genres', as: 'all_genres'
  get '/shows/genre' => 'shows#genre', as: 'genre'
  get '/shows/scrape' => 'shows#scrape', as: 'scrape'
  get '/shows/tv_tonight' => 'shows#tv_tonight', as: 'tv_tonight'
  get '/shows/dvd' => 'shows#dvd', as: 'dvd'
  get '/shows/imdb_search_title' => 'shows#imdb_search_title', as: 'imdb_search_title'
  resources :shows
  get '/whatsbetter/first_run' => 'whatsbetter#first_run', as: 'first_run'
  get '/whatsbetter/clear_skips' => 'whatsbetter#destroy_skips', as: 'clear_skips'
  get '/whatsbetter/rate_shows' => 'whatsbetter#rate_shows', as: 'rate_shows'
  get '/whatsbetter/top_rated' => 'whatsbetter#top_rated', as: 'whatsbetter_top_rated'
  get '/whatsbetter/rate_show' => 'whatsbetter#rate_show', as: 'rate_show'
  get '/whatsbetter/rate_group' => 'whatsbetter#rate_group', as: 'rate_group'
  get '/whatsbetter/rate_confusing' => 'whatsbetter#rate_confusing', as: 'rate_confusing'
  get '/whatsbetter/rate_show_recs' => 'whatsbetter#rate_show_recs', as: 'rate_show_recs'
  resources :whatsbetter
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<%#
require 'ruby-prof'
RubyProf.start
%>
<!DOCTYPE html>
<html>
  <head>
    <title>TvShowRecommender</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if logged_in? %>
      <%= link_to current_user.name, current_user %>, <%= link_to 'log out', logout_path, method: :delete %>
    <% end %>
  </head>

  <body>
    <%= @notice if @notice %>
    <% if ApplicationRecord.errors.any?  %>
      <ol>
      <% ApplicationRecord.errors_show.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ol>
    <% end %>

    <table><tr>
        <td><%= link_to 'TV Today', tv_tonight_path %></td>
        <td><%= link_to 'TV Last Week', tv_tonight_path(start_date: ApplicationRecord.todays_date(-7), end_date: ApplicationRecord.todays_date(-1)) %></td>
        <td><%= link_to 'TV Next Week', tv_tonight_path(start_date: ApplicationRecord.todays_date(1), end_date: ApplicationRecord.todays_date(7)) %></td>
    </table>
<div>
  <%= form_tag '/shows', method:"get" do %>
    <%= text_field_tag :q %>
    <%= submit_tag 'search' %>
  <% end %>
</div>

    <%= yield %>
    <ul>
      <li><%= link_to 'TV Tonight', tv_tonight_path %></li>
      <li><%= link_to 'New DVD', dvd_path %></li>
      <li><%= link_to 'Rate Top TV', whatsbetter_top_rated_path %></li>
      <li><%= link_to 'Rate Top Movies', whatsbetter_top_rated_movies_path %></li>
  </body>
</html>

<%#
results = RubyProf.stop

File.open "#{::Rails.root}/tmp/profile-graph.html", 'w' do |file|
    RubyProf::GraphHtmlPrinter.new(results).print(file)
end

File.open "#{::Rails.root}/tmp/profile-flat.txt", 'w' do |file|
    RubyProf::FlatPrinter.new(results).print(file)
end

# File.open "#{::Rails.root}/tmp/profile-tree.prof", 'w' do |file|
#     RubyProf::CallTreePrinter.new(results).print(file)
# end
%>